language: php
sudo: false
cache:
  directories:
  - "$HOME/.composer/cache"
before_script:
- composer install
stages:
- qa
- deploy
jobs:
  include:
  - stage: qa
    php: 7.2
    script: &1
    - "./vendor/bin/php-cs-fixer fix --dry-run"
    - "./vendor/bin/phpstan analyse"
    - "./vendor/bin/phpunit"
  - stage: qa
    php: 7.3
    script: *1
  - stage: Deploy
    php: 7.2
    script:
    - "./vendor/bin/box compile"
    deploy:
      provider: releases
      skip_cleanup: true
      api_key:
        secure: W5HR+Qex63vHy055xjav2/5GT5Glv7kpl838TN5yvUo/aAhXtx5C8pzpLertV/eAldZt0JofVuBw3KIXPb/6RScOp1XvIcZoCfSUBBKUXD7Tm++rwyON2iLvAYBTkOZt+asPbiPCaeJ6mAC8O6fo5UlYvaFzB93DTw5AiZz81/Rao3Xpkqrqv4Yq6RNARBg8045UDVYLJ2P5VRGYlpL5+jUdBKea04iI/L7UZhf9QqoxJ6pKfP/ts6QyomLJTcXD8GWzjOcPH5fLNQRPbDMG4wUpQjzWDAkPcK4oRUm8ZDFnGctSKsrBltYgqUTLwLo012dqv9o8/GOJdL96H26nJCw8eIEXDqFhpsSAgMbw8c1//cIfLU5LWzpxLqo9hFI2vPMMsE7GeTIj49tlAiArcgBJBo+n8ODom6J5rFo/kRKqJ4oSatDMWa6F6VDmlurkQkMyUo4ZQpFBVb5P6dsf79H6SvQ5yTnDaYjs8Q2YU4g3x10NZTuCuXsdBXhSyD8ox/fJp83JxJeB7/wXnozPt/6RdWT3fO6hxmQvGAOvOnfemknUKCBie+x6VO6xI0GVweNe+RmNLrG8b0j+n2bpjp8hqwWqN6OovHHAegT+fOLeF2nOU/KbLmibuNgeoPrKw0awxmMV8fL8tctF/1GLkGUIJBgbLWYipfPsT4PU2sA=
      file: bin/fink.phar
      on:
        repo: dantleech/fink
        tags: true
